on: 
  push:
    branches:
      - QA
name: Publish QA SocialGrow
jobs:
  web-deploy:
    name: Deploy To QA SocialGrow
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v3
    
    - name: ğŸ”¨ Set up Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: ğŸ“¦ Install dependencies
      run: |
        npm install
        # cp env-QA .env
        # cat .env

    - name: ğŸ› ï¸ Build project
      run: |
        npm run build

    - name: Prepare Folder
      run: |
        mkdir deploy_folder
        mv api ./deploy_folder
        mv build/* ./deploy_folder
        ls ./deploy_folder
    
    - name: ğŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        protocol: ftp
        server: ${{ secrets.FTP_QA_SERVER }} 
        username: ${{ secrets.FTP_QA_USERNAME }}
        password: ${{ secrets.FTP_QA_PASSWORD }}
        server-dir: ${{ secrets.FTP_QA_SERVER_DIR }}
        local-dir: deploy_folder
